### ISSUE TITLE
Indices Error

### ISSUE THREAD

**Issue by anushkb** [aferral/Structure-from-motion-python#2]
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    graphList[i] = triangulateGraph(graphList[i],imageSize)
  File "/content/drive/SFM/utils/graph.py", line 84, in triangulateGraph
    x[cnt,:] = newGraph.obsVal[newGraph.ObsIdx[i][ind],:]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by njanirudh** [comment]
Were you able to solve this?

**Comment by NavneetSajwan** [comment]
I also have the same error.

**Comment by ZHANG-SHI-CHANG** [comment]
write as x[cnt,:] = newGraph.obsVal[int(newGraph.ObsIdx[i][ind]), :]

**Comment by heyjoey7** [comment]
Were you able to solve this?

**Comment by heyjoey7** [comment]
> Traceback (most recent call last):
> File "main.py", line 110, in
> graphList[i] = triangulateGraph(graphList[i],imageSize)
> File "/content/drive/SFM/utils/graph.py", line 84, in triangulateGraph
> x[cnt,:] = newGraph.obsVal[newGraph.ObsIdx[i][ind],:]
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices



> Traceback (most recent call last):
> File "main.py", line 110, in
> graphList[i] = triangulateGraph(graphList[i],imageSize)
> File "/content/drive/SFM/utils/graph.py", line 84, in triangulateGraph
> x[cnt,:] = newGraph.obsVal[newGraph.ObsIdx[i][ind],:]
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I also have the same error. Have you solved it?
